# Generated by Django 4.1.7 on 2023-03-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image_post_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='UserPost',
        ),
    ]
