# Generated by Django 4.1.7 on 2023-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_otp', '0002_alter_emailotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
