# Generated by Django 4.1.7 on 2023-04-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_otp', '0003_alter_emailotp_code_alter_emailotp_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP Email Verification'},
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
