# Generated by Django 4.1.7 on 2023-04-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_link_auth', '0002_alter_emailverification_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Link Email Verification'},
        ),
    ]
