# Generated by Django 4.1.7 on 2023-04-04 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('email_link_auth', '0004_alter_emailverification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
